// react/src/App.jsx
import { useState } from 'react';
import { ExclamationTriangleIcon, CheckCircleIcon } from '@heroicons/react/24/outline';
import {
  InaccessibleButton,
  AccessibleButton,
  AccessibleForm,
  AccessibleModal,
  AccessibleDropdown
} from './components';

function App() {
  const [activeComponent, setActiveComponent] = useState('menu');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedOption, setSelectedOption] = useState(null);
  const [focusedMenuIndex, setFocusedMenuIndex] = useState(0);

  const dropdownOptions = [
    { id: 1, label: 'Opção 1' },
    { id: 2, label: 'Opção 2' },
    { id: 3, label: 'Opção 3' }
  ];

  const menuItems = [
    { id: 'buttons', label: 'Botões Acessíveis vs Inacessíveis', description: 'Demonstra diferença entre botões acessíveis e inacessíveis' },
    { id: 'form', label: 'Formulário Acessível', description: 'Formulário com validação e acessibilidade completa' },
    { id: 'modal', label: 'Modal Acessível', description: 'Modal com gerenciamento de foco e navegação por teclado' },
    { id: 'dropdown', label: 'Dropdown Acessível', description: 'Dropdown com navegação por setas e ARIA attributes' }
  ];

  const renderComponent = () => {
    switch (activeComponent) {
      case 'buttons':
        return (
          <section>
            <h2>Botões Acessíveis vs Inacessíveis</h2>
            <p>Demonstra a diferença entre implementação correta e incorreta de botões.</p>

            <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <ExclamationTriangleIcon style={{ width: '20px', height: '20px', color: '#dc3545' }} />
              Botões Inacessíveis
            </h3>
            <div style={{ marginBottom: '30px', padding: '20px', border: '1px solid #dc3545' }}>
              <InaccessibleButton />
            </div>

            <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <CheckCircleIcon style={{ width: '20px', height: '20px', color: '#28a745' }} />
              Botões Acessíveis
            </h3>
            <div style={{ marginBottom: '30px', padding: '20px', border: '1px solid #28a745', background: '#d4edda' }}>
              <AccessibleButton />
            </div>
          </section>
        );

      case 'form':
        return (
          <section>
            <h2>Formulário Acessível</h2>
            <p>Formulário com validação em tempo real, mensagens de erro acessíveis e labels corretos.</p>
            <AccessibleForm />
          </section>
        );

      case 'modal':
        return (
          <section>
            <h2>Modal Acessível</h2>
            <p>Modal com trap de foco, navegação por teclado e gerenciamento de foco adequado.</p>
            <button onClick={() => setIsModalOpen(true)} style={{ background: '#007bff', color: 'white', padding: '12px 24px', border: 'none', borderRadius: '4px', fontSize: '16px', cursor: 'pointer', transition: 'background-color 0.2s' }}
              onMouseEnter={(e) => e.target.style.backgroundColor = '#0056b3'}
              onMouseLeave={(e) => e.target.style.backgroundColor = '#007bff'}>
              Abrir Modal
            </button>
            <AccessibleModal
              isOpen={isModalOpen}
              onClose={() => setIsModalOpen(false)}
              title="Modal de Demonstração"
            >
              <p>Este é um modal acessível com gerenciamento de foco.</p>
              <p>Use Tab para navegar dentro do modal, Escape para fechar.</p>
              <p>O foco é automaticamente direcionado para o modal quando aberto.</p>
            </AccessibleModal>
          </section>
        );

      case 'dropdown':
        return (
          <section>
            <h2>Dropdown Acessível</h2>
            <p>Dropdown com navegação por teclado (setas), suporte a Enter/Escape e atributos ARIA corretos.</p>
            <AccessibleDropdown
              options={dropdownOptions}
              value={selectedOption}
              onChange={setSelectedOption}
              placeholder="Selecione uma opção"
            />
            {selectedOption && (
              <p>Selecionado: {selectedOption.label}</p>
            )}
          </section>
        );

      default:
        return (
          <div>
            <h2>Menu de Demonstrações</h2>
            <p>Selecione um componente para ver a demonstração prática de acessibilidade:</p>
            <div
              style={{ display: 'grid', gap: '20px', marginTop: '20px' }}
              onKeyDown={(e) => {
                switch (e.key) {
                  case 'ArrowDown':
                    e.preventDefault();
                    setFocusedMenuIndex(prev => prev < menuItems.length - 1 ? prev + 1 : 0);
                    break;
                  case 'ArrowUp':
                    e.preventDefault();
                    setFocusedMenuIndex(prev => prev > 0 ? prev - 1 : menuItems.length - 1);
                    break;
                  case 'Enter':
                  case ' ':
                    e.preventDefault();
                    setActiveComponent(menuItems[focusedMenuIndex].id);
                    break;
                }
              }}
              tabIndex={0}
            >
              {menuItems.map((item, index) => (
                <div
                  key={item.id}
                  style={{
                    border: `2px solid ${focusedMenuIndex === index ? '#dc3545' : '#007bff'}`,
                    borderRadius: '8px',
                    padding: '20px',
                    cursor: 'pointer',
                    transition: 'all 0.2s',
                    backgroundColor: focusedMenuIndex === index ? '#ffe6e6' : 'transparent',
                    outline: focusedMenuIndex === index ? '2px solid #dc3545' : 'none'
                  }}
                  onClick={() => setActiveComponent(item.id)}
                  onMouseEnter={(e) => {
                    e.target.style.backgroundColor = '#f8f9fa';
                    e.target.style.borderColor = '#007bff';
                  }}
                  onMouseLeave={(e) => {
                    e.target.style.backgroundColor = focusedMenuIndex === index ? '#ffe6e6' : 'transparent';
                    e.target.style.borderColor = focusedMenuIndex === index ? '#dc3545' : '#007bff';
                  }}
                  role="button"
                  tabIndex={0}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      setActiveComponent(item.id);
                    }
                  }}
                  aria-label={`Abrir demonstração: ${item.label}`}
                >
                  <h3 style={{ margin: '0 0 10px 0', color: '#007bff' }}>{item.label}</h3>
                  <p style={{ margin: 0, color: '#6c757d' }}>{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        );
    }
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
      <header style={{ marginBottom: '30px', borderBottom: '2px solid #007bff', paddingBottom: '20px' }}>
        <h1 style={{ color: '#007bff', margin: '0 0 10px 0' }}>Componentes Acessíveis - React</h1>
        <p style={{ margin: 0, color: '#6c757d' }}>
          Demonstrações práticas de componentes acessíveis seguindo as diretrizes WCAG
        </p>
        {activeComponent !== 'menu' && (
          <button
            onClick={() => setActiveComponent('menu')}
            style={{
              marginTop: '15px',
              padding: '8px 16px',
              background: '#6c757d',
              color: 'white',
              border: 'none',
              borderRadius: '4px',
              cursor: 'pointer',
              transition: 'background-color 0.2s'
            }}
            onMouseEnter={(e) => e.target.style.backgroundColor = '#5a6268'}
            onMouseLeave={(e) => e.target.style.backgroundColor = '#6c757d'}
            aria-label="Voltar ao menu principal"
          >
            ← Voltar ao Menu
          </button>
        )}
      </header>

      <main>
        {renderComponent()}
      </main>

      <footer style={{ marginTop: '40px', paddingTop: '20px', borderTop: '1px solid #ddd', color: '#6c757d', fontSize: '14px' }}>
        <p>
          <strong>Dicas de Acessibilidade:</strong><br />
          • Use Tab para navegar entre elementos interativos<br />
          • Pressione Escape para fechar modais ou cancelar ações<br />
          • Use setas do teclado para navegar em listas e menus<br />
          • Elementos focáveis têm indicadores visuais (quando estilos são aplicados)
        </p>
      </footer>
    </div>
  );
}

export default App;

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ModalComponent } from './components/modal/modal.component';
import { CommonModule } from '@angular/common';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { heroXMark, heroExclamationTriangle, heroCheckCircle } from '@ng-icons/heroicons/outline';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, ModalComponent, CommonModule, NgIconComponent],
  providers: [provideIcons({ heroXMark, heroExclamationTriangle, heroCheckCircle })],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'angular';
  activeComponent = 'menu';
  isModalOpen = false;
  focusedMenuIndex = 0;

  menuItems = [
    {
      id: 'buttons',
      label: 'Botões Acessíveis vs Inacessíveis',
      description: 'Demonstra diferença entre botões acessíveis e inacessíveis'
    },
    {
      id: 'form',
      label: 'Formulário Acessível',
      description: 'Formulário com validação e acessibilidade completa'
    },
    {
      id: 'modal',
      label: 'Modal Acessível',
      description: 'Modal com gerenciamento de foco e navegação por teclado'
    }
  ];

  openModal() {
    this.isModalOpen = true;
  }

  closeModal() {
    this.isModalOpen = false;
  }

  confirmAction() {
    alert('Ação confirmada!');
    this.isModalOpen = false;
  }

  setActiveComponent(componentId: string) {
    this.activeComponent = componentId;
  }

  goBackToMenu() {
    this.activeComponent = 'menu';
  }

  onMenuKeyDown(event: KeyboardEvent) {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        this.focusedMenuIndex = this.focusedMenuIndex < this.menuItems.length - 1 ? this.focusedMenuIndex + 1 : 0;
        break;
      case 'ArrowUp':
        event.preventDefault();
        this.focusedMenuIndex = this.focusedMenuIndex > 0 ? this.focusedMenuIndex - 1 : this.menuItems.length - 1;
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        this.setActiveComponent(this.menuItems[this.focusedMenuIndex].id);
        break;
    }
  }
}

<div style="padding: 20px; font-family: Arial, sans-serif;">
  <header style="margin-bottom: 30px; border-bottom: 2px solid #007bff; padding-bottom: 20px;">
    <h1 style="color: #007bff; margin: 0 0 10px 0;">Componentes Acessíveis - Angular</h1>
    <p style="margin: 0; color: #6c757d;">
      Demonstrações práticas de componentes acessíveis seguindo as diretrizes WCAG
    </p>
    <button
      *ngIf="activeComponent !== 'menu'"
      (click)="goBackToMenu()"
      style="margin-top: 15px; padding: 8px 16px; background: #6c757d; color: white; border: none; border-radius: 4px; cursor: pointer;"
      aria-label="Voltar ao menu principal"
    >
      ← Voltar ao Menu
    </button>
  </header>

  <main>
    <div *ngIf="activeComponent === 'menu'">
      <h2>Menu de Demonstrações</h2>
      <p>Selecione um componente para ver a demonstração prática de acessibilidade:</p>
      <div
        style="display: grid; gap: 20px; margin-top: 20px;"
        tabindex="0"
        (keydown)="onMenuKeyDown($event)"
      >
        <div
          *ngFor="let item of menuItems; let i = index"
          (click)="setActiveComponent(item.id)"
          (keydown.enter)="setActiveComponent(item.id)"
          (keydown.space)="setActiveComponent(item.id)"
          tabindex="0"
          role="button"
          [style.border-color]="focusedMenuIndex === i ? '#dc3545' : '#007bff'"
          [style.background-color]="focusedMenuIndex === i ? '#ffe6e6' : 'transparent'"
          [style.outline]="focusedMenuIndex === i ? '2px solid #dc3545' : 'none'"
          style="border-radius: 8px; padding: 20px; cursor: pointer; transition: all 0.2s;"
          [attr.aria-label]="'Abrir demonstração: ' + item.label"
        >
          <h3 style="margin: 0 0 10px 0; color: #007bff;">{{ item.label }}</h3>
          <p style="margin: 0; color: #6c757d;">{{ item.description }}</p>
        </div>
      </div>
    </div>

    <section *ngIf="activeComponent === 'buttons'">
      <h2>Botões Acessíveis vs Inacessíveis</h2>
      <p>Demonstra a diferença entre implementação correta e incorreta de botões.</p>

      <h3 style="display: flex; align-items: center; gap: 8px;">
        <ng-icon name="heroExclamationTriangle" style="color: #dc3545;"></ng-icon>
        Botões Inacessíveis
      </h3>
      <div style="margin-bottom: 30px; padding: 20px; border: 1px solid #dc3545; background: #f8d7da;">
        <div style="background: #007bff; color: white; padding: 10px 20px; margin: 10px; cursor: pointer; display: inline-block; border-radius: 4px;">
          Clique aqui (div como botão)
        </div>
        <button style="margin: 10px; display: flex; align-items: center;">
          <ng-icon name="heroXMark"></ng-icon>
        </button>
        <a href="#" style="background: #28a745; color: white; padding: 10px 20px; margin: 10px; text-decoration: none; display: inline-block; border-radius: 4px;">
          Executar ação (link agindo como botão)
        </a>
      </div>

      <h3 style="display: flex; align-items: center; gap: 8px;">
        <ng-icon name="heroCheckCircle" style="color: #28a745;"></ng-icon>
        Botões Acessíveis
      </h3>
      <div style="margin-bottom: 30px; padding: 20px; border: 1px solid #28a745; background: #d4edda;">
        <button type="button" style="background: #28a745; color: white; padding: 10px 20px; margin: 10px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px;">
          Clique aqui
        </button>
        <button type="button" aria-label="Fechar janela" style="background: #dc3545; color: white; padding: 10px 15px; margin: 10px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px;">
          <ng-icon name="heroXMark"></ng-icon>
        </button>
        <button type="button" style="background: #ffc107; color: #000; padding: 10px 20px; margin: 10px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px;">
          Executar ação
        </button>
      </div>
    </section>

    <section *ngIf="activeComponent === 'form'">
      <h2>Formulário Acessível</h2>
      <p>Formulário com validação em tempo real, mensagens de erro acessíveis e labels corretos.</p>

      <form style="max-width: 600px; margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
        <fieldset style="border: 2px solid #007bff; border-radius: 4px; padding: 20px; margin-bottom: 20px;">
          <legend style="font-weight: bold; padding: 0 10px; color: #007bff;">Informações de Cadastro</legend>

          <div style="margin-bottom: 20px;">
            <label for="name" style="display: block; font-weight: bold; margin-bottom: 5px; color: #333;">
              Nome completo *
            </label>
            <input
              type="text"
              id="name"
              style="width: 100%; padding: 12px; border: 2px solid #ccc; border-radius: 4px; font-size: 16px; box-sizing: border-box;"
              required
              aria-required="true"
              aria-describedby="name-help"
            />
            <div id="name-help" style="font-size: 14px; color: #6c757d; margin-top: 5px;">
              Digite seu nome completo como aparece no documento
            </div>
          </div>

          <div style="margin-bottom: 20px;">
            <label for="email" style="display: block; font-weight: bold; margin-bottom: 5px; color: #333;">
              E-mail *
            </label>
            <input
              type="email"
              id="email"
              style="width: 100%; padding: 12px; border: 2px solid #ccc; border-radius: 4px; font-size: 16px; box-sizing: border-box;"
              required
              aria-required="true"
              aria-describedby="email-help"
            />
            <div id="email-help" style="font-size: 14px; color: #6c757d; margin-top: 5px;">
              Usaremos este e-mail para contato
    </div>
      </div>

          <div style="margin-bottom: 20px;">
            <label style="display: flex; align-items: center; font-weight: normal; cursor: pointer;">
              <input
                type="checkbox"
                style="margin-right: 10px; width: auto;"
                aria-describedby="newsletter-help"
              />
              Quero receber newsletter
            </label>
            <div id="newsletter-help" style="font-size: 14px; color: #6c757d; margin-top: 5px;">
              Você pode cancelar a qualquer momento
      </div>
    </div>
        </fieldset>

        <button type="submit" style="background: #007bff; color: white; padding: 12px 30px; border: none; border-radius: 4px; font-size: 16px; cursor: pointer; font-weight: bold;">
          Criar conta
        </button>
      </form>
    </section>

    <section *ngIf="activeComponent === 'modal'">
      <h2>Modal Acessível</h2>
      <p>Modal com trap de foco, navegação por teclado e gerenciamento de foco adequado.</p>
      <button (click)="openModal()" style="background: #007bff; color: white; padding: 12px 24px; border: none; border-radius: 4px; font-size: 16px; cursor: pointer;">
        Abrir Modal
      </button>
    </section>
</main>

  <app-modal
    [isOpen]="isModalOpen"
    [title]="'Modal de Demonstração'"
    [showFooter]="true"
    [confirmText]="'Confirmar Ação'"
    (close)="closeModal()"
    (confirm)="confirmAction()"
  >
    <p>Este é um modal acessível com gerenciamento de foco.</p>
    <p>Use Tab para navegar dentro do modal, Escape para fechar.</p>
    <p>O foco é automaticamente direcionado para o modal quando aberto.</p>
  </app-modal>

  <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #6c757d; font-size: 14px;">
    <p>
      <strong>Dicas de Acessibilidade:</strong><br />
      • Use Tab para navegar entre elementos interativos<br />
      • Pressione Escape para fechar modais ou cancelar ações<br />
      • Elementos focáveis têm indicadores visuais<br />
      • Labels e descrições ajudam tecnologias assistivas
    </p>
  </footer>
</div>

<router-outlet />
